### PR TITLE
Fix #336: FacebookClient throws NullReferenceException when calling GetTaskAsync in Windows 10 app 

### LINKED ISSUE #336: FacebookClient throws NullReferenceException when calling GetTaskAsync in Windows 10 app
null value is assigned to HttpWebRequest.ContentType in PrepareRequest function, which triggers a NullReferenceException.

This is the stack trace:
```
   at System.Net.HttpWebRequest.set_ContentType(String value)
   at Facebook.HttpWebRequestWrapper.set_ContentType(String value)
   at Facebook.FacebookClient.PrepareRequest(HttpMethod httpMethod, String path, Object parameters, Type resultType, Stream& input, Boolean& containsEtag, IList`1& batchEtags)
   at Facebook.FacebookClient.ApiAsync(HttpMethod httpMethod, String path, Object parameters, Type resultType, Object userState)
   at Facebook.FacebookClient.ApiTaskAsync(HttpMethod httpMethod, String path, Object parameters, Type resultType, Object userState, CancellationToken cancellationToken, IProgress`1 uploadProgress)
   at Facebook.FacebookClient.ApiTaskAsync(HttpMethod httpMethod, String path, Object parameters, Type resultType, Object userState, CancellationToken cancellationToken)
   at Facebook.FacebookClient.GetTaskAsync(String path, Object parameters, CancellationToken cancellationToken, Type resultType)
   at Facebook.FacebookClient.GetTaskAsync(String path, Object parameters, CancellationToken cancellationToken)
   at Facebook.FacebookClient.GetTaskAsync(String path)
```

### PR DESCRIPTION
**Pull request by nguyenquyhy**
null value is assigned to HttpWebRequest.ContentType, which causes a NullReferenceException.

### CODE REVIEW

File: Source/Facebook/FacebookClient.cs [hunk 1]
```diff
@@ -602,7 +602,10 @@ private HttpHelper PrepareRequest(HttpMethod httpMethod, string path, object par
                     throw new ArgumentOutOfRangeException("httpMethod");
             }
 
-            request.ContentType = contentType;
+            if (contentType != null)
```
Comment (prabirshrestha) [inline Source/Facebook/FacebookClient.cs]: can you use `string.IsNullOrEmpty` and also remove the braces like for etag below.

**Comment by nguyenquyhy** [comment]
Changed!
